server:
  port: 8082

spring:
  application:
    name: instrument
  datasource:
    url: 'jdbc:h2:mem:instrumentdb'
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'

management:
  endpoints:
    web:
      exposure:
        include: '*'