spring:
  application:
    name: eurekaserver
  cloud:
    config:
      enabled: false

server:
  port: 8761

# Désactiver l'auto-enregistrement du serveur lui-même comme client Eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
